env:
  browser: true
  es2020: true
  node: true

extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 11
  sourceType: module
  project: tsconfig.json

plugins:
  - "@typescript-eslint"

rules:
  linebreak-style:
    - error
    - windows

  quotes:
    - error
    - single

  comma-dangle:
    - error
    - always-multiline

  no-useless-rename: error
  object-shorthand: error

  no-multiple-empty-lines:
    - error
    - max: 1
      maxBOF: 0
      maxEOF: 0

  semi: "off"
  "@typescript-eslint/semi":
    - error
    - always

  indent: "off"
  "@typescript-eslint/indent":
    - error
    - 2

  "@typescript-eslint/array-type":
    - error
    - default: array-simple

  "@typescript-eslint/member-delimiter-style": error
