name: Test and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test and Build ( ${{ matrix.os.name }}, Node.js v${{ matrix.node-version }} )

    runs-on: ${{ matrix.os.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm test
      - run: npm run build

    strategy:
      matrix:
        os:
          - name: Ubuntu
            image: ubuntu-latest
          - name: macOS
            image: macos-latest
          - name: Windows
            image: windows-latest
        node-version:
          - 18.x
          - 20.x
          - 21.x
          - 22.x
